# VM3 - Ubuntu Server (DHCPv6 Server)
# Requirements:
#   sudo apt install dnsmasq
#
# Place this file at: /etc/dnsmasq.conf
# Then: sudo systemctl restart dnsmasq

port=0
interface=ens33
dhcp-range=2001:db8::100,2001:db8::200,64,12h
dhcp-option=option6:dns-server,[2001:db8::2]
